name: Build

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    tags:
      - "v*"
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: "recursive"

      - name: Fetch Tags
        run: |
          git fetch --tags --force

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27d
          add-to-path: true
          local-cache: true

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: module

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Build
        run: ./build.sh

      - name: Collect artifact name
        run: |
          echo "release=$(basename -s .zip build/*.zip)" >> $GITHUB_ENV

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.release }}
          path: build/*.zip
          archive: false

      - name: Get tag annotation
        id: tag
        if: github.ref_type == 'tag'
        run: |
          {
            echo 'annotation<<EOF'
            git for-each-ref "${GITHUB_REF}" --format '%(contents)'
            echo 'EOF'
          } >>"${GITHUB_OUTPUT}"

      - name: Create Release
        if: github.ref_type == 'tag'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.tag.outputs.annotation }}
          files: build/*.zip
          prerelease: ${{ contains(github.ref_name, '-') }}
